spring:
   datasource:
      username: space_marine
      password: space_marine
      url: jdbc:mysql://localhost:3306/space_marine
      
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true   
      
   
   